repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml

  - repo: local
    hooks:
      - id: formatting
        name: Formatting
        entry: make format
        language: system
        files: \.(py|cpp|hpp)$
      # - id: tests
      #   name: Tests
      #   entry: make tests
      #   language: system