name: dnazen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - mpi4py=3.1
  - libgcc=7 # gcc version is a bit low for conda. But at least it's working.
  - pip
  # the rest of dependencies are in `pyproject.toml`