# no longer includes special tokens in ngram-training
RESOURCE_DIR=../resources
DNAZEN_DATA_VERSION=v10.0
DNAZEN_NGRAM_VERSION=v10.0
# DNAZEN_PRETRAIN_VERSION=v9.4
DNAZEN_FINETUNE_VERSION=v10.0
NGRAM_TRAIN_METHOD=pmi
NGRAM_ENCODER_DIR=${RESOURCE_DIR}/ngrams/${NGRAM_TRAIN_METHOD}-${DNAZEN_NGRAM_VERSION}

NGRAM_ENCODER_MSPECIES=${NGRAM_ENCODER_DIR}/ngram-encoder-mspecies.json
NGRAM_ENCODER_HG38=${NGRAM_ENCODER_DIR}/ngram-encoder-hg38-all.json
NGRAM_ENCODER_GUE=${NGRAM_ENCODER_DIR}/ngram-encoder-gue-all.json

# 更新数据路径到测试目录
export DNAZEN_PRETRAIN_RAW_DATA_DIR=../data/pretrain
export DNAZEN_PRETRAIN_DATA_DIR=../data/dnazen-pretrain-${DNAZEN_DATA_VERSION}
export NGRAM_ENCODER_DIR=${NGRAM_ENCODER_DIR}
export ALL_NGRAM_ENCODERS="${NGRAM_ENCODER_MSPECIES} ${NGRAM_ENCODER_HG38} ${NGRAM_ENCODER_GUE}"
export MAIN_NGRAM_ENCODER_DIR=${NGRAM_ENCODER_DIR}/ngram-encoder-merged.json
export SIDE_NGRAM_ENCODER_DIR=${NGRAM_ENCODER_GUE}
export CORE_NGRAM_DIR=${RESOURCE_DIR}/core_ngrams-${DNAZEN_NGRAM_VERSION}.json
export FINETUNE_DATA_DIR=../data/finetune
export FINETUNE_OUT_DIR=${RESOURCE_DIR}/finetune-output-${DNAZEN_FINETUNE_VERSION}
export FINETUNE_CHECKPOINT_STEP=15000
export MAIN_NGRAM_ENCODER_DATA_SOURCES=mspecies,gue_all
export NGRAM_TRAIN_METHOD=${NGRAM_TRAIN_METHOD}
export MERGED_NGRAM_DIR=${RESOURCE_DIR}/ngrams/ngram-encoder-merged-${DNAZEN_NGRAM_VERSION}.json

export NGRAM_MIN_NGRAM_FREQ=5
export NGRAM_MIN_TOKEN_FREQ=5
export NGRAM_MAX_LEN=6
export NGRAM_MIN_PMI=5
export DNAZEN_PRETRAIN_LR=8e-5 